ALTER TABLE tickets ADD COLUMN IF NOT EXISTS categoria VARCHAR(20);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS fecha_evento TIMESTAMP;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS zona_nombre VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS compuerta_nombre VARCHAR(100);
