ALTER TABLE asientos
    ADD COLUMN IF NOT EXISTS existente BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS expira_en TIMESTAMP;
