ALTER TABLE eventos ADD COLUMN IF NOT EXISTS reingreso_habilitado BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS numero_asiento VARCHAR(20);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS permite_reingreso BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE precios_zona ADD COLUMN IF NOT EXISTS nombre_zona VARCHAR(100);

ALTER TABLE recintos DROP COLUMN IF EXISTS modelo_negocio;
ALTER TABLE recintos DROP COLUMN IF EXISTS monto_fijo;
